// Bundles the rasterization worker into a single self-contained string so it
// ships inlined in the library and can be instantiated from a Blob URL — no
// dependency on the consumer's bundler handling worker files. The output is
// written to src/raster/worker-source.ts (committed; regenerated by this
// script, which runs before `build` and `dev`).

const ENTRY = 'src/raster/raster.worker.ts'
const OUT = 'src/raster/worker-source.ts'

const result = await Bun.build({
  entrypoints: [ENTRY],
  target: 'browser',
  format: 'esm',
  minify: true,
})

if (!result.success) {
  console.error('build-worker: failed to bundle the worker')
  for (const log of result.logs) console.error(log)
  process.exit(1)
}

const code = await result.outputs[0]!.text()
const file = `// GENERATED by scripts/build-worker.ts — do not edit.
// Bundled, self-contained source of ${ENTRY}, inlined so the worker ships in
// the library and is instantiated via a Blob URL (see rasterize-worker.ts).
export const WORKER_SOURCE = ${JSON.stringify(code)}
`

await Bun.write(OUT, file)
console.log(`build-worker: wrote ${OUT} (${code.length} bytes)`)
